# Generated by Django 3.0.5 on 2020-06-13 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_date', models.DateField()),
                ('file_count', models.IntegerField()),
                ('sum_total', models.CharField(max_length=50)),
                ('sum_de', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sum_cr', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producer', models.CharField(max_length=50)),
                ('audit', models.CharField(max_length=50)),
                ('cashier', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Voucher.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='AccountDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=250)),
                ('account_sub', models.CharField(max_length=50)),
                ('debit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('credit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Voucher.Account')),
            ],
        ),
    ]
