# Generated by Django 3.0.5 on 2020-06-14 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voucher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='category',
            field=models.CharField(default='s', max_length=20),
            preserve_default=False,
        ),
    ]
