# Generated by Django 3.0.5 on 2020-07-02 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voucher', '0002_subject_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': '会计科目', 'verbose_name_plural': '会计科目'},
        ),
        migrations.AlterModelOptions(
            name='subjectdetail',
            options={'verbose_name': '二级会计科目', 'verbose_name_plural': '二级会计科目'},
        ),
        migrations.AlterField(
            model_name='account',
            name='account_date',
            field=models.DateField(verbose_name='记账日期'),
        ),
        migrations.AlterField(
            model_name='account',
            name='file_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='sum_total',
            field=models.CharField(max_length=50, verbose_name='合计'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='category',
            field=models.CharField(choices=[('debit', '借'), ('credit', '贷')], max_length=20, verbose_name='类别'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='科目编码'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='科目名称'),
        ),
        migrations.AlterField(
            model_name='subjectdetail',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='科目编码'),
        ),
        migrations.AlterField(
            model_name='subjectdetail',
            name='name',
            field=models.CharField(max_length=50, verbose_name='科目名称'),
        ),
    ]
