# Generated by Django 3.0.5 on 2020-07-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voucher', '0003_auto_20200702_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountdetail',
            name='account',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
